import { SignInButton, useUser } from '@clerk/nextjs'
import Head from 'next/head'
import { type RouterOutputs, api } from '~/utils/api'

import dayjs from 'dayjs'
import relativeTime from 'dayjs/plugin/relativeTime'
import Image from 'next/image'

dayjs.extend(relativeTime)

const CreatePostWizard = () => {
  const user = useUser()

  console.log(user)

  if (!user.user) return null

  return (
    <div className="flex w-full gap-3">
      <Image
        src={user.user.imageUrl}
        alt="profile image"
        className="h-14 w-14 rounded-full"
        height={56}
        width={56}
      />
      <input
        placeholder="Type some emojis"
        className="grow bg-transparent outline-none"
      />
    </div>
  )
}

type PostWithAuthor = RouterOutputs['posts']['getAll'][number]

const PostView = (props: PostWithAuthor) => {
  const { post, author } = props
  return (
    <div
      key={post.id}
      className=" align- flex gap-4 border-b border-slate-400 p-8"
    >
      <Image
        src={author.profileImageUrl}
        alt={`${author.name}'s profile image`}
        className="h-14 w-14"
        height={56}
        width={56}
      />
      <div className="flex flex-col">
        <div className="flex gap-1 font-bold text-slate-400">
          <span>{`@${author.name} ·`}</span>
          <span className="font-thin">{`${dayjs(
            post.createdAt
          ).fromNow()}`}</span>
        </div>
        <span>{post.content}</span>
      </div>
    </div>
  )
}

export default function Home() {
  const user = useUser()
  const { data, isLoading } = api.posts.getAll.useQuery()

  if (isLoading) return <div>Loading...</div>

  if (!data) return <div>Something went wrong</div>

  return (
    <>
      <Head>
        <title>Chirp - An emoji only twitter clone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            {!user.isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {user.isSignedIn && <CreatePostWizard />}
          </div>
          <div className="flex flex-col">
            {data?.map((postWithAuthor) => (
              <PostView key={postWithAuthor.post.id} {...postWithAuthor} />
            ))}
          </div>
        </div>
      </main>
    </>
  )
}
